Models/Restaurant.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace RestaurantReviewer.Models
{
    public class Restaurant
    {
        [Key] public int RestaurantId { get; set; }
        public string RestaurantName { get; set; }
        public string Street { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public string Hours { get; set; }
        public string Keywords { get; set; }
        public ICollection<Review> Reviews { get; set; }
        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }
        public string ImageUrl { get; set; }
        public string CarouselImage1 { get; set; }
        public string CarouselImage2 { get; set; }
        public string CarouselImage3 { get; set; }
        public int RateCount
        {
            get { return Reviews.Count; }
        }
        public int RateAverage
        {
            get { return (Reviews.Sum(m => m.Rate)); }
        }

        internal void Delete(int id)
        {
            throw new NotImplementedException();
        }
    }
}

ViewModels/RestaurantViewModel.cs
using RestaurantReviewer.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace RestaurantReviewer.ViewModels
{
    public class RestaurantViewModel
    {
        public string RestaurantName { get; set; }
        public int RestaurantId { get; set; }
        public string Street { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public string Hours { get; set; }
        public string Keywords { get; set; }
        public string CarouselImage1 { get; set; }
        public string CarouselImage2 { get; set; }
        public string CarouselImage3 { get; set; }
        public DateTime Date { get; set; }
        public string ReviewDescription { get; set; }
        public virtual User User { get; set; }
        public string Username { get; set; }
        public int Rate { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public ICollection<Review> Reviews { get; set; }
        public int RateCount
        {
            get { return Reviews.Count; }
        }
        public int RateAverage
        {
            get { return (Reviews.Sum(m => m.Rate)); }
        }
    }
}

Controllers/FavoriteCartController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using RestaurantReviewer.Interfaces;
using RestaurantReviewer.Models;
using RestaurantReviewer.ViewModels;

namespace RestaurantReviewer.Controllers
{
    public class FavoriteCartController : Controller
    {
        private readonly IRestaurantRepository _restaurantRepository;
        private readonly FavoriteCart _favoriteCart;
        public FavoriteCartController(IRestaurantRepository restaurantRepository, FavoriteCart favoriteCart) 
        {
            _restaurantRepository = restaurantRepository;
            _favoriteCart = favoriteCart;
        }
        public ViewResult Index()
        {
            var items = _favoriteCart.GetFavoriteRestaurants();
            _favoriteCart.FavoriteRestaurants = items;

            var fcvm = new FavoriteCartViewModel
            {
                FavoriteCart = _favoriteCart

            };
            return View(fcvm);
        }
       
        public RedirectToActionResult AddToFavoriteCart(int restaurantId)
        {
            var selectedRestaurant = _restaurantRepository.Restaurant.FirstOrDefault(p => p.RestaurantId==restaurantId);
            if (selectedRestaurant != null)
            {
                _favoriteCart.AddToCart(selectedRestaurant);
            }
            return RedirectToAction("Index");
        }
        public RedirectToActionResult RemoveFromFavoriteCart(int restaurantId)
        {
            var selectedRestaurant = _restaurantRepository.Restaurant.FirstOrDefault(p => p.RestaurantId == restaurantId);
            if (selectedRestaurant != null)
            {
                _favoriteCart.RemoveFromCart(selectedRestaurant);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/RestaurantsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using Newtonsoft.Json;
using RestaurantReviewer.Interfaces;
using RestaurantReviewer.Models;
using RestaurantReviewer.ViewModels;

namespace RestaurantReviewer.Controllers
{
    public class RestaurantsController : Controller
    {
            private readonly IRestaurantRepository _restaurantRepository;
            private readonly ICategoryRepository _categoryRepository;
            private readonly IReviewRepository _reviewRepository;
            private readonly Context _context;

      public RestaurantsController(IRestaurantRepository restaurantRepository, ICategoryRepository categoryRepository ,IReviewRepository reviewRepository,Context context)
            {
                _restaurantRepository = restaurantRepository;
                _categoryRepository = categoryRepository;
                _reviewRepository = reviewRepository;
                _context = context;
            }
        public async Task<IActionResult> Restaurant(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = _restaurantRepository.Restaurant.FirstOrDefault(m => m.RestaurantId == id);
           
            if (restaurant == null)
            {
                return NotFound();
            }
            var restaurantVM = new RestaurantViewModel
            {
                CarouselImage1 = restaurant.CarouselImage1,
                CarouselImage2 = restaurant.CarouselImage2,
                CarouselImage3 = restaurant.CarouselImage3,
                RestaurantId = restaurant.RestaurantId,
                RestaurantName = restaurant.RestaurantName,
                Phone = restaurant.Phone,
                Hours = restaurant.Hours,
                Keywords = restaurant.Keywords,
                Website = restaurant.Website,
                
            
            };

            return View(restaurantVM);
        }
       
        public IActionResult List(int id)
        {
            IEnumerable<Category> categories;
            IEnumerable<Restaurant> restaurants;
            string currentCategory = string.Empty;
            int _category = id;
            categories = _categoryRepository.Category.OrderBy(n => n.CategoryId);
            if (id == 0)
            {
                restaurants = _restaurantRepository.Restaurant.OrderBy(n => n.RestaurantId);
                currentCategory = "All restaurants";
            }
            else
            {
                if (_category == 1)
                {
                    restaurants = _restaurantRepository.Restaurant.Where(p => p.Category.NameCategory.Equals("bistro"));
                    currentCategory = "Bistro";
                }
                else if (_category == 2)
                {
                    restaurants = _restaurantRepository.Restaurant.Where(p => p.Category.NameCategory.Equals("pizza"));
                    currentCategory = "Pizza places";
                }
                else if (_category == 3)
                {
                    restaurants = _restaurantRepository.Restaurant.Where(p => p.Category.NameCategory.Equals("traditional"));
                    currentCategory = "Traditional restaurants";
                }

                else if (_category == 4)
                {
                    restaurants = _restaurantRepository.Restaurant.Where(p => p.Category.NameCategory.Equals("fancy"));
                    currentCategory = "Fancy restaurants";
                }

                else 
                {
                    restaurants = _restaurantRepository.Restaurant.Where(p => p.Category.NameCategory.Equals("sweets"));
                    currentCategory = "Cookies and Sweets";
                }

            }

            var listRestaurants = new RestaurantList
            {
                Restaurants = restaurants,
                CurrentCategory = currentCategory,
                Categories = categories
            };

            return View(listRestaurants);
        }
        [HttpPost]
        public ActionResult SendReview(RestaurantViewModel restaurantViewModel, int rank)
        {
            var username = HttpContext.Session.GetString("username");
            restaurantViewModel.Date = DateTime.Now;
            restaurantViewModel.Username = _context.Users.Single(a=>a.Username==username).Username;
            restaurantViewModel.Rate = rank;

            Review review = new Review();
            review.Date = restaurantViewModel.Date;
            review.Username = restaurantViewModel.Username;
            review.ReviewDescription = restaurantViewModel.ReviewDescription;
            review.User = restaurantViewModel.User;
            review.RestaurantId = restaurantViewModel.RestaurantId;
            review.Rate = restaurantViewModel.Rate;
            _context.Reviews.Add(review);
            _context.SaveChanges();

            return RedirectToAction("Restaurant", "Restaurants", new { id=restaurantViewModel.RestaurantId });
        }
        public IActionResult ReviewList(int? id)
        {
            List<Review> ReviewList = new List<Review>();
            if (id == null)
            {
                return NotFound();
            }
            Restaurant restaurant = _context.Restaurants.FirstOrDefault(m => m.RestaurantId == id);
            if(_context.Reviews.Where(m => m.RestaurantId == restaurant.RestaurantId).ToList() == null)
            {
                return NotFound();
            }
            ReviewList = _context.Reviews.Where(m => m.RestaurantId == restaurant.RestaurantId).ToList();
            return View(ReviewList);
            
        }

        // GET: Restaurants/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_categoryRepository.Category, "CategoryId", "CategoryId");
            return View();
        }

        // POST: Restaurants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RestaurantId,RestaurantName,Street,Phone,Website,Hours,CategoryId,ImageUrl,CarouselImage1,CarouselImage2,CarouselImage3")] Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                _restaurantRepository.Add(restaurant);
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_categoryRepository.Category, "CategoryId", "CategoryId", restaurant.CategoryId);
            return View(restaurant);
        }

        // GET: Restaurants/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = _restaurantRepository.Restaurant.Where(c => c.RestaurantId == id).FirstOrDefault();
            if (restaurant == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_restaurantRepository.Category, "CategoryId", "CategoryId", restaurant.CategoryId);
            return View(restaurant);
        }

        // POST: Restaurants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RestaurantId,RestaurantName,Street,Phone,Website,Hours,CategoryId,ImageUrl,CarouselImage1,CarouselImage2,CarouselImage3")] Restaurant restaurant)
        {
            if (id != restaurant.RestaurantId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _restaurantRepository.Update(restaurant);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RestaurantExists(restaurant.RestaurantId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_categoryRepository.Categories, "CategoryId", "CategoryId", restaurant.CategoryId);
            return View(restaurant);
        }

        private bool RestaurantExists(int id)
        {
            return _restaurantRepository.Restaurant.Any(e => e.RestaurantId == id);
        }

        //GET: Restaurants/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurants.Include(r => r.Category).FirstOrDefaultAsync(m => m.RestaurantId == id);
            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }

        // POST: Restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var restaurant = _restaurantRepository.Restaurant.Where(c => c.RestaurantId == id).FirstOrDefault();
            restaurant.Delete(id);

Views/Restaurants/Create.cshtml
@model RestaurantReviewer.Models.Restaurant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RestaurantName" class="control-label"></label>
                <input asp-for="RestaurantName" class="form-control" />
                <span asp-validation-for="RestaurantName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Website" class="control-label"></label>
                <input asp-for="Website" class="form-control" />
                <span asp-validation-for="Website" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hours" class="control-label"></label>
                <input asp-for="Hours" class="form-control" />
                <span asp-validation-for="Hours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarouselImage1" class="control-label"></label>
                <input asp-for="CarouselImage1" class="form-control" />
                <span asp-validation-for="CarouselImage1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarouselImage2" class="control-label"></label>
                <input asp-for="CarouselImage2" class="form-control" />
                <span asp-validation-for="CarouselImage2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarouselImage3" class="control-label"></label>
                <input asp-for="CarouselImage3" class="form-control" />
                <span asp-validation-for="CarouselImage3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Restaurants/Delete.cshtml
@model RestaurantReviewer.Models.Restaurant

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RestaurantName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RestaurantName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Website)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Website)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hours)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hours)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryId)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarouselImage1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarouselImage1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarouselImage2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarouselImage2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarouselImage3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarouselImage3)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RestaurantId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Restaurants/Details.cshtml
@model RestaurantReviewer.Models.Restaurant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RestaurantName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RestaurantName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Website)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Website)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hours)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hours)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarouselImage1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarouselImage1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarouselImage2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarouselImage2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarouselImage3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarouselImage3)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.RestaurantId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Restaurants/Edit.cshtml
@model RestaurantReviewer.Models.Restaurant

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RestaurantId" />
            <div class="form-group">
                <label asp-for="RestaurantName" class="control-label"></label>
                <input asp-for="RestaurantName" class="form-control" />
                <span asp-validation-for="RestaurantName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Website" class="control-label"></label>
                <input asp-for="Website" class="form-control" />
                <span asp-validation-for="Website" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hours" class="control-label"></label>
                <input asp-for="Hours" class="form-control" />
                <span asp-validation-for="Hours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarouselImage1" class="control-label"></label>
                <input asp-for="CarouselImage1" class="form-control" />
                <span asp-validation-for="CarouselImage1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarouselImage2" class="control-label"></label>
                <input asp-for="CarouselImage2" class="form-control" />
                <span asp-validation-for="CarouselImage2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarouselImage3" class="control-label"></label>
                <input asp-for="CarouselImage3" class="form-control" />
                <span asp-validation-for="CarouselImage3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Restaurants/Restaurant.cshtml
@model RestaurantReviewer.ViewModels.RestaurantViewModel

@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href=~/css/restaurantinfostyle.css>
    
</head>
<body>


    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="@Model.CarouselImage1" alt="First slide" height="450px">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="@Model.CarouselImage2" alt="Second slide" height="450px">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="@Model.CarouselImage3" alt="Third slide" height="450px">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="container container-fluid info">

        <h1>
            @Html.DisplayFor(model => model.RestaurantName)
            <a class="btn btn-light" id="cartButton" asp-action="AddToFavoriteCart" asp-controller="FavoriteCart" asp-route-restaurantId="@Model.RestaurantId">
                <svg class="bi bi-heart" width="1em" height="1em" viewBox="0 0 16 16" fill="black" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 01.176-.17C12.72-3.042 23.333 4.867 8 15z" clip-rule="evenodd" />
                </svg>
            </a>

        </h1>

        <p>@Html.DisplayFor(model => model.Street)</p>
        <p>@Html.DisplayFor(model => model.Phone)</p>
        <p><a href="@Html.DisplayFor(model => model.Website)">Website</a></p>
        <p>@Html.DisplayFor(model => model.Keywords)</p>
        <div>
            <p>
                @Html.DisplayFor(model => model.Hours)
            </p>
        </div>
    </div>

    <div class="container container-fluid info">
        <div class="row bootstrap snippets">
            <div class="col-xl-12">
                <div class="comment-wrapper">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3>
                                @*Reviews @Model.RateCount*@
                                <h4>
                                    <a asp-controller="Restaurants"
                                       asp-action="ReviewList"
                                       asp-route-id="@Model.RestaurantId">See Reviews
                                    </a>
                                    
                                </h4>
                                
                                @* stars *@
                            </h3>


                        </div>
                        <div class="panel-body">
                            @if (@HttpContextAccessor.HttpContext.Session.GetString("username") == null)
                            {
                                <a href="@Url.Action("Login", "User")">Login to post your review</a>
                            }
                            else
                            {
                                @using (Html.BeginForm("SendReview", "Restaurants", FormMethod.Post))
                                {
                                    for(int i = 1; i <= 5; i++)
                                    {
                                        <input type="radio" id="rank" name="rank" value="@i" />@i
                                    }
                                    <div id="rateyo"></div>
                                    @Html.TextAreaFor(model => model.ReviewDescription, new { cols = 350, rows = 5 })
                                    <td>&nbsp;</td>
                                    <input type="submit" value="Send" />
                                    @Html.HiddenFor(model => model.RestaurantId)
                                }
                               
                            }
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>